// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('Pyoopil.Services').factory('Auth', [
    '$cookieStore', '$q', 'Form', function($cookieStore, $q, Form) {
      var Auth;
      return new (Auth = (function() {
        function Auth() {
          this.getAuthToken();
        }

        Auth.prototype.getAuthToken = function() {
          return this.token = $cookieStore.get('token') || false;
        };

        Auth.prototype.authorize = function(callback) {
          this.currentUser = this.getCurrentUser();
          return this.currentUser.then(function(data) {
            return callback(true);
          }, function(err) {
            return callback(false);
          });
        };

        Auth.prototype.setCurrentUser = function(user) {
          return this.currentUser = user;
        };

        Auth.prototype.getCurrentUser = function() {
          var defer, token;
          defer = $q.defer();
          token = this.getAuthToken();
          if ((token != null) && token) {
            defer.resolve(token);
          } else {
            defer.reject(token);
          }
          return defer.promise;
        };

        Auth.prototype.logout = function() {
          $cookieStore.remove('token');
          this.currentUser = {};
          return true;
        };

        return Auth;

      })());
    }
  ]);

}).call(this);

//# sourceMappingURL=authentication.map
