// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('Pyoopil.Services').factory('DataModel', [
    function() {
      var DataModel;
      return new (DataModel = (function() {
        function DataModel() {}

        DataModel.prototype.init = function(scope) {
          return this.scope = scope;
        };

        DataModel.prototype.setWatcher = function(args) {
          var subject;
          subject = args;
          if (angular.isDefined(subject)) {
            return this.scope.$watch(subject, (function(_this) {
              return function(newVal, oldVal) {
                if (newVal !== oldVal) {
                  console.log(newVal);
                  return _this.scope.$broadcast('UPDATE.' + subject, newVal);
                }
              };
            })(this), true);
          }
        };

        return DataModel;

      })());
    }
  ]);

}).call(this);

//# sourceMappingURL=DataModel.map
