// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('Pyoopil.Services').factory('EventEmitter', [
    '$document', function($document) {
      var EventEmitter;
      return EventEmitter = (function() {
        function EventEmitter() {}

        EventEmitter.prototype.init = function(scope) {
          return this.$scope = scope;
        };

        EventEmitter.prototype.emit = function(evt, data, scope) {
          if (angular.isDefined(scope)) {
            return scope.$broadcast(evt, data);
          } else {
            return this.$scope.$broadcast(evt, data);
          }
        };

        EventEmitter.prototype.broadcast = function(evt, data, scope) {
          if (angular.isDefined(scope)) {
            return scope.$emit(evt, data);
          } else {
            return this.$scope.$emit(evt, data);
          }
        };

        return EventEmitter;

      })();
    }
  ]);

}).call(this);

//# sourceMappingURL=EventEmitter.map
