// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('Pyoopil.Services').factory('Form', [
    '$window', '$http', 'Utilities', function($window, $http, Utilities) {
      var Form;
      return new (Form = (function() {
        var self;

        self = Form;

        function Form() {
          self.url = Utilities.getPath();
        }

        Form.prototype.init = function(scope) {
          return this.scope = scope;
        };

        Form.prototype.postData = function(data, url) {
          var xhr;
          xhr = $http({
            method: 'POST',
            url: url,
            data: data
          });
          return xhr;
        };

        Form.prototype.getData = function(url) {
          var xhr;
          xhr = $http({
            method: 'GET',
            url: url
          });
          return xhr;
        };

        return Form;

      })());
    }
  ]);

}).call(this);

//# sourceMappingURL=form.map
