// Generated by CoffeeScript 1.7.1
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  angular.module('Pyoopil.Services').factory('UserService', [
    '$window', 'Form', 'CRUD', '$cookieStore', '$q', 'Auth', function($window, Form, CRUD, $cookieStore, $q, Auth) {
      var UserService;
      return new (UserService = (function() {
        function UserService() {
          this.login = __bind(this.login, this);
        }

        UserService.prototype.init = function(scope) {
          return this.scope = scope;
        };

        UserService.prototype.login = function(data, callback) {
          var cb, deferred, promise;
          cb = callback || angular.noop;
          deferred = $q.defer();
          promise = Form.postData(data, CRUD.LOGIN);
          return promise.then((function(_this) {
            return function(data) {
              if (data.data.status) {
                $cookieStore.put('token', data.data.data.auth_token);
                deferred.resolve(data.data.data);
                return cb();
              }
            };
          })(this), (function(_this) {
            return function(err) {
              _this.logout();
              deferred.reject(data);
              return cb(err);
            };
          })(this));
        };

        return UserService;

      })());
    }
  ]);

}).call(this);

//# sourceMappingURL=UserService.map
