// Generated by CoffeeScript 1.7.1
(function () {
  var __hasProp = {}.hasOwnProperty,
    __extends = function (child, parent) {
      for (var key in parent) {
        if (__hasProp.call(parent, key)) child[key] = parent[key];
      }

      function ctor() {
        this.constructor = child;
      }
      ctor.prototype = parent.prototype;
      child.prototype = new ctor();
      child.__super__ = parent.prototype;
      return child;
    };

  angular.module('Pyoopil.Services').factory('Utilities', [
    '$document', 'EventEmitter', '$window',
    function ($document, EventEmitter, $window) {
      var Utilities;
      return new(Utilities = (function (_super) {
        __extends(Utilities, _super);

        function Utilities() {
          this.modalPath = '/pyoopil/js/app/partials/overlays/';
          this.currentModal = false;
          this._body = angular.element($document[0].body);
        }

        Utilities.prototype.init = function (scope) {
          Utilities.__super__.init.call(this, scope);
          this.$scope.template = {};
          return this.$scope.showModal = false;
        };

        Utilities.prototype.openModal = function (template) {
          this.$scope.template.url = this.modalPath + template + '.html';
          this.$scope.showModal = true;
          if (!this.$scope.$$phase) {
            this.$scope.$digest();
          }
          this._body.on('click', '.close-link', (function (_this) {
            return function (e) {
              e.preventDefault();
              return _this.closeModal(e);
            };
          })(this));
          return this.emit('openModal');
        };

        Utilities.prototype.closeModal = function (e) {
          this.$scope.template.url = null;
          this.$scope.showModal = true;
          this.emit('closeModal');
          if (!this.$scope.$$phase) {
            return this.$scope.$digest();
          }
        };

        Utilities.prototype.getPath = function () {
          return $window.location.origin + $window.location.pathname;
        };

        return Utilities;

      })(EventEmitter));
    }
  ]);

}).call(this);

//# sourceMappingURL=utilities.map