// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('Pyoopil.Directives').directive('login', [
    '$state', 'Utilities', function($state, Utilities) {
      return {
        restrict: 'E',
        template: '<button name="login_btn" value="login" id="dialog-link">Login</button>',
        link: function(scope, elem, attrs) {
          var $resetPass;
          elem.on('click', function() {
            return Utilities.openModal('login');
          });
          $resetPass = elem.find('#for-pass');
          return $resetPass.on('click', function(e) {
            e.preventDefault();
            Utilities.closeModal();
            $state.go('reset');
            return false;
          });
        }
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=login.map
