// Generated by CoffeeScript 1.7.1
(function () {
  angular.module('Pyoopil.Directives').directive('register', [
    'mainService',
    function (mainService) {
      return {
        restrict: 'E',
        templateUrl: '/pyoopil/js/app/partials/register.html',
        link: function (scope, elem, attrs) {
          var $close, $registration;
          $registration = elem.find('#assign-dialog');
          $close = elem.find('a.close-link');
          scope.register = {};
          scope.submit = function (form) {
            var data, post;
            toastr.clear();
            if (form.$valid) {
              data = {
                'data[AppUser][firstname]': scope.register.firstname,
                'data[AppUser][lastname]': scope.register.lastname,
                'data[AppUser][email]': scope.register.email,
                'data[AppUser][institution]': scope.register.institution
              };
              post = mainService.postRegistration(data);
              post.then(function (data) {
                return toastr.success('Registration Successful');
              }, function () {
                return toastr.error('Registration Failed !');
              });
            }
            return '';
          };
          elem.on('click', function () {
            scope.$parent.$emit('openModal');
            return $registration.show();
          });
          return $close.on('click', function (e) {
            scope.$parent.$emit('closeModal');
            $registration.hide();
            return false;
          });
        }
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=register.map