// Generated by CoffeeScript 1.7.1
(function () {
  angular.module('Pyoopil.Directives').controller('resetpassCtrl', [
    '$scope',
    function ($scope) {
      return $scope.validPass = false;
    }
  ]).directive('resetpass', [
    '$http',
    function ($http) {
      return {
        restrict: 'E',
        scope: {},
        controller: 'resetpassCtrl',
        templateUrl: '/pyoopil/js/app/partials/reset-pass-form.html',
        link: function (scope, elem, attrs, ctrl) {
          var $newPass, $newPassConfirm, $submit, score;
          $newPass = angular.element('#reset_pass');
          $newPassConfirm = angular.element('#reset_pass_confirm');
          $submit = angular.element('#submit');
          score = 0;
          scope.passStrength = '';
          scope.login = {};
          $newPass.passMeter(function (score) {
            if (score < 40) {
              scope.passStrength = 'weak';
            } else if (score < 90) {
              scope.passStrength = 'medium';
            } else {
              scope.passStrength = 'strong';
            }
            if (!scope.$$phase) {
              return scope.$digest();
            }
          });
          scope.$watch('login.reset_pass_confirm', function (newVal, oldVal) {
            if (newVal !== oldVal) {
              if ((scope.passStrength != null) && (scope.login.reset_pass === scope.login.reset_pass_confirm)) {
                return scope.validPass = true;
              } else {
                return scope.validPass = false;
              }
            }
          });
          return $submit.on('click', function (e) {
            return e.preventDefault();
          });
        }
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=resetpass.map