// Generated by CoffeeScript 1.7.1
(function() {
  var announcementsCtrl, app,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  app = angular.module('Pyoopil.Controllers');

  announcementsCtrl = (function(_super) {
    __extends(announcementsCtrl, _super);

    function announcementsCtrl() {
      return announcementsCtrl.__super__.constructor.apply(this, arguments);
    }

    announcementsCtrl.register(app);

    announcementsCtrl.inject('$scope', 'announcementService', 'Notify', 'FileUploader');

    announcementsCtrl.prototype.initialize = function() {
      this.$scope.pageNo = 1;
      this.$scope.permissions = {};
      this.$scope.isSubmitted = false;
      this.$scope.uploader = new this.FileUploader({
        filters: [
          {
            name: 'singleUpload',
            fn: function(item, options) {
              return this.queue.length === 0;
            }
          }
        ]
      });
      this.announcementService.init(this.$scope);
      return this.$scope.submit = (function(_this) {
        return function() {
          var data, form;
          _this.$scope.isSubmitted = true;
          form = _this.$scope.announcementForm;
          if (form.$invalid) {
            _this.Notify.alert('Please enter valid details', 'error');
            return;
          }
          if (form.$valid) {
            data = {
              "Announcement": _this.$scope.Announcements
            };
            _this.announcementService.postForm(data);
          }
          return '';
        };
      })(this);
    };

    return announcementsCtrl;

  })(BaseCtrl);

}).call(this);

//# sourceMappingURL=announcementsCtrl.map
