// Generated by CoffeeScript 1.7.1
(function() {
  var app, classroomsCtrl,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  app = angular.module('Pyoopil.Controllers');

  classroomsCtrl = (function(_super) {
    __extends(classroomsCtrl, _super);

    function classroomsCtrl() {
      this.joinClassroom = __bind(this.joinClassroom, this);
      this.createClassroom = __bind(this.createClassroom, this);
      return classroomsCtrl.__super__.constructor.apply(this, arguments);
    }

    classroomsCtrl.register(app);

    classroomsCtrl.inject('$scope', 'classroomService', 'Notify', 'Utilities', '$rootScope');

    classroomsCtrl.prototype.initialize = function() {
      this.$scope.pageNo = 1;
      this.$scope.permissions = {};
      this.$scope.isSubmitted = false;
      return this.classroomService.init(this.$scope);
    };

    classroomsCtrl.prototype.createClassroom = function() {
      var data, form;
      this.$scope.isSubmitted = true;
      form = this.$scope.createClassroomForm;
      if (form.$valid) {
        data = {
          "Classroom": this.$scope.classroom
        };
        return this.classroomService.postForm('add.json', data, function(data) {
          return this.broadcast('Classroom', data, this.$scope);
        });
      }
    };

    classroomsCtrl.prototype.showJoinClassroom = function() {
      $(".newjoin").hide();
      $(".accessclass").show();
      return '';
    };

    classroomsCtrl.prototype.hideJoinClassroom = function() {
      $(".newjoin").show();
      $(".accessclass").hide();
      return '';
    };

    classroomsCtrl.prototype.joinClassroom = function() {
      var data;
      if (this.$scope.accessCode == null) {
        this.Notify.alert('Please enter a valid Access Code', 'error');
        return;
      }
      data = {
        'Classroom': {
          'access_code': this.$scope.accessCode
        }
      };
      this.classroomService.postForm('join.json', data, function(data) {
        return this.emit('READ.Classroom', data, this.$scope);
      });
      return this.$scope.accessCode = '';
    };

    return classroomsCtrl;

  })(BaseCtrl);

}).call(this);

//# sourceMappingURL=classroomsCtrl.map
