// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('Pyoopil.Controllers').controller('logoutCtrl', [
    '$scope', 'Auth', '$state', function($scope, Auth, $state) {
      return Auth.logout();
    }
  ]);

}).call(this);

//# sourceMappingURL=logoutCtrl.map
