// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('Pyoopil.Controllers').controller('mainCtrl', [
    '$scope', 'Utilities', 'EventEmitter', function($scope, Utilities, EventEmitter) {
      Utilities.init($scope);
      return $scope.$on('Classroom', function(evt, data) {
        if (data.Classroom.is_private) {
          $scope.code = data.Classroom.access_code;
          Utilities.openModal('private-classroom-success-message');
        } else {
          Utilities.openModal('public-classroom-success-message');
        }
        return $scope.$broadcast('READ.Classroom', data);
      });
    }
  ]);

}).call(this);

//# sourceMappingURL=mainCtrl.map
