// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  angular.module('Pyoopil.Services').factory('announcementService', [
    'Utilities', 'CSBase', function(Utilities, CSBase) {
      var announcementService;
      return new (announcementService = (function(_super) {
        __extends(announcementService, _super);

        function announcementService() {
          announcementService.__super__.constructor.apply(this, arguments);
        }

        announcementService.prototype.init = function(scope) {
          announcementService.__super__.init.call(this, scope);
          this.path += this.currentClassroom + '/Announcements/';
          this.getUrl = 'getannouncements.json?page=';
          this.getCallback = function(data) {
            return this.emit('READ.Announcements', data);
          };
          return this.getDatum();
        };

        announcementService.prototype.postForm = function(data) {
          var url;
          url = 'add.json';
          return announcementService.__super__.postForm.call(this, url, data, data);
        };

        return announcementService;

      })(CSBase));
    }
  ]);

}).call(this);

//# sourceMappingURL=announcements.map
