// Generated by CoffeeScript 1.7.1
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  angular.module('Pyoopil.Services').factory('classroomService', [
    'Utilities', 'CSBase', function(Utilities, CSBase) {
      var ClassroomService;
      return new (ClassroomService = (function(_super) {
        __extends(ClassroomService, _super);

        function ClassroomService() {
          this.postForm = __bind(this.postForm, this);
          ClassroomService.__super__.constructor.apply(this, arguments);
        }

        ClassroomService.prototype.init = function(scope) {
          ClassroomService.__super__.init.call(this, scope);
          this.getUrl = 'getclassrooms.json?page=';
          this.getCallback = function(data) {
            return this.emit('READ.Classrooms', data);
          };
          return this.getDatum();
        };

        ClassroomService.prototype.postForm = function(url, data, cb) {
          if (angular.isDefined(cb)) {
            this.getCallback = cb;
          } else {
            this.getCallback = function(data) {
              return this.emit('READ.Classrooms', data);
            };
          }
          return ClassroomService.__super__.postForm.call(this, url, data, data);
        };

        ClassroomService.prototype.setCurrentClassroom = function(id) {
          return ClassroomService.__super__.setCurrentClassroom.call(this, id);
        };

        return ClassroomService;

      })(CSBase));
    }
  ]);

}).call(this);

//# sourceMappingURL=classrooms.map
