// Generated by CoffeeScript 1.7.1
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  angular.module('Pyoopil.Services').factory('discussionService', [
    'Utilities', 'CSBase', function(Utilities, CSBase) {
      var discussionService;
      return new (discussionService = (function(_super) {
        __extends(discussionService, _super);

        function discussionService() {
          this.postForm = __bind(this.postForm, this);
          discussionService.__super__.constructor.apply(this, arguments);
        }

        discussionService.prototype.init = function(scope) {
          discussionService.__super__.init.call(this, scope);
          this.path += this.currentClassroom + '/Discussions/';
          this.getUrl = 'getdiscussions.json?page=';
          this.getCallback = function(data) {
            console.log(data);
            return this.emit('READ.Discussions', data);
          };
          return this.getDatum();
        };

        discussionService.prototype.postForm = function(url, data, cb) {
          if (angular.isDefined(cb)) {
            this.getCallback = cb;
          } else {
            this.getCallback = function(data) {
              return this.emit('READ.Discussions', data);
            };
          }
          return discussionService.__super__.postForm.call(this, url, data, data);
        };

        return discussionService;

      })(CSBase));
    }
  ]);

}).call(this);

//# sourceMappingURL=discussions.map
