// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  angular.module('Pyoopil.Services').factory('libraryService', [
    'Utilities', 'CSBase', function(Utilities, CSBase) {
      var libraryService;
      return new (libraryService = (function(_super) {
        __extends(libraryService, _super);

        function libraryService() {
          libraryService.__super__.constructor.apply(this, arguments);
        }

        libraryService.prototype.init = function(scope) {
          libraryService.__super__.init.call(this, scope);
          this.path += this.currentClassroom + '/Library/';
          this.getUrl = 'getTopicsList.json?page=';
          this.getCallback = function(data) {
            return this.emit('READ.Libraries', data);
          };
          return this.getDatum();
        };

        return libraryService;

      })(CSBase));
    }
  ]);

}).call(this);

//# sourceMappingURL=library.map
