// Generated by CoffeeScript 1.7.1
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  angular.module('Pyoopil.Services').factory('peopleService', [
    'Utilities', 'CSBase', function(Utilities, CSBase) {
      var PeopleService;
      return new (PeopleService = (function(_super) {
        __extends(PeopleService, _super);

        function PeopleService() {
          this.postForm = __bind(this.postForm, this);
          PeopleService.__super__.constructor.apply(this, arguments);
        }

        PeopleService.prototype.init = function(scope) {
          PeopleService.__super__.init.call(this, scope);
          this.getUrl = 'getpeople.json.json?page=';
          this.path += this.currentClassroom + '/People/';
          this.getCallback = function(data) {
            return this.emit('READ.Peoples', data);
          };
          return this.getDatum();
        };

        PeopleService.prototype.postForm = function(url, data, cb) {
          if (angular.isDefined(cb)) {
            this.getCallback = cb;
          } else {
            this.getCallback = function(data) {
              return this.emit('READ.Peoples', data);
            };
          }
          return PeopleService.__super__.postForm.call(this, url, data, data);
        };

        return PeopleService;

      })(CSBase));
    }
  ]);

}).call(this);

//# sourceMappingURL=people.map
