// Generated by CoffeeScript 1.7.1
(function () {
  angular.module('Pyoopil.Directives').directive('reply', [
    function () {
      return {
        restrict: 'A',
        scope: {
          reply: '='
        },
        templateUrl: '/pyoopil/js/app/partials/sandbox/reply.html',
        link: function (scope, elem, attrs) {}
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=reply.map