// Generated by CoffeeScript 1.7.1
(function () {
  angular.module('Pyoopil.Directives').directive('replies', [
    'EventEmitter', 'Notify',
    function (EventEmitter, Notify) {
      return {
        restrict: 'E',
        templateUrl: '/pyoopil/js/app/partials/sandbox/replies.html',
        link: function (scope, elem, attrs) {
          var Replies;
          return new(Replies = (function () {
            function Replies() {
              this.addListeners();
            }

            Replies.prototype.addListeners = function () {
              return scope.$on('READ.Replies', (function (_this) {
                return function (evt, data) {
                  return _this.renderReplies(evt, data);
                };
              })(this));
            };

            Replies.prototype.renderReplies = function (evt, replies) {
              if (_.isEmpty(replies)) {
                Notify.alert('No More Replies to load', 'error');
                return;
              }
              return angular.forEach(replies, function (reply) {
                if (reply.hasOwnProperty('Reply')) {
                  return scope.replies.unshift(reply.Reply);
                } else {
                  return scope.replies.push(reply);
                }
              });
            };

            return Replies;

          })());
        }
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=replies.map