// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('Pyoopil.Directives').controller('scrollbarCtrl', [
    '$scope', function($scope) {
      return $scope.hasScrollReached = false;
    }
  ]).directive('scrollbar', [
    function() {
      return {
        restrict: 'A',
        link: function(scope, elem, attrs) {
          var $tinyscrollbar, $tsb, $vp;
          $tsb = angular.element('.tinyscrollbar');
          $vp = $tsb.find('.viewport');
          $tsb.tinyscrollbar({
            thumbSize: 34
          });
          $tinyscrollbar = $tsb.data("plugin_tinyscrollbar");
          scope.$on('UPDATE.Scroll', function(evt, isRelative) {
            scope.hasScrollReached = false;
            if ((isRelative != null) && isRelative) {
              return $tinyscrollbar.update('relative');
            } else {
              return $tinyscrollbar.update();
            }
          });
          return $vp.on('endOfScroll', function(e) {
            if (!scope.hasScrollReached) {
              scope.hasScrollReached = true;
              return scope.$emit('END.Scroll');
            }
          });
        }
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=scrollbar.map
