// Generated by CoffeeScript 1.7.1
(function () {
  angular.module('Pyoopil.Directives').factory('Tiles', [
    '$timeout',
    function ($timeout) {
      var Tiles;
      return Tiles = (function () {
        function Tiles() {
          return {
            restrict: 'E',
            templateUrl: '/pyoopil/js/app/partials/Classrooms/classroom-tile.html'
          };
        }

        return Tiles;

      })();
    }
  ]);

}).call(this);

//# sourceMappingURL=tiles.map