// Generated by CoffeeScript 1.7.1
(function () {
  angular.module('Pyoopil.Directives').directive('announcements', [
    'EventEmitter', 'Notify',
    function (EventEmitter, Notify) {
      return {
        restrict: 'E',
        templateUrl: '/pyoopil/js/app/partials/Classrooms/announcement.html',
        link: function (scope, elem, attrs) {
          var Classrooms;
          return new(Classrooms = (function () {
            function Classrooms() {
              scope.announcements = [];
              this.addListeners();
            }

            Classrooms.prototype.addListeners = function () {
              return scope.$on('READ.Announcements', (function (_this) {
                return function (evt, data) {
                  return _this.renderAnnouncements(evt, data);
                };
              })(this));
            };

            Classrooms.prototype.renderAnnouncements = function (evt, announcements) {
              if (_.isEmpty(announcements)) {
                Notify.alert('No More Announcements to load', 'error');
                return;
              }
              return angular.forEach(announcements, function (announcement) {
                return scope.announcements.push(announcement);
              });
            };

            return Classrooms;

          })());
        }
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=announcements.map