// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('Pyoopil.Directives').directive('classroom', [
    'classroomService', function(classroomService) {
      return {
        restrict: 'A',
        scope: {
          classroom: '='
        },
        link: function(scope, elem, attrs) {
          if (scope.$parent.$last) {
            classroomService.rendered();
          }
          return elem.on('click', function() {
            return classroomService.setCurrentClassroom(scope.classroom.UsersClassroom.classroom_id);
          });
        }
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=classroom.map
