// Generated by CoffeeScript 1.7.1
(function () {
  angular.module('Pyoopil.Directives').directive('discussions', [
    'EventEmitter', 'Notify',
    function (EventEmitter, Notify) {
      return {
        restrict: 'E',
        templateUrl: '/pyoopil/js/app/partials/Classrooms/discussion.html',
        link: function (scope, elem, attrs) {
          var Discussions;
          return new(Discussions = (function () {
            function Discussions() {
              scope.discussions = [];
              this.isInitial = true;
              this.addListeners();
            }

            Discussions.prototype.addListeners = function () {
              scope.$on('READ.Discussions', (function (_this) {
                return function (evt, data) {
                  return _this.renderDiscussions(evt, data);
                };
              })(this));
              return scope.$on('REMOVE.Discussion', (function (_this) {
                return function (evt, id) {
                  return _this.removeDiscussion(id);
                };
              })(this));
            };

            Discussions.prototype.renderDiscussions = function (evt, discussions) {
              if (_.isEmpty(discussions)) {
                Notify.alert('No More Discussions to load', 'error');
                return;
              }
              angular.forEach(discussions, (function (_this) {
                return function (discussion) {
                  if (_this.isInitial) {
                    return scope.discussions.push(discussion);
                  } else {
                    return scope.discussions.unshift(discussion);
                  }
                };
              })(this));
              return this.isInitial = false;
            };

            Discussions.prototype.removeDiscussion = function (id) {
              return scope.discussions = _.reject(scope.discussions, function (discussion) {
                return discussion.Discussion.id === id;
              });
            };

            return Discussions;

          })());
        }
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=discussions.map