// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  angular.module('Pyoopil.Directives').directive('discussionType', [
    'EventEmitter', 'Notify', function(EventEmitter, Notify) {
      return {
        restrict: 'A',
        scope: {
          discussionType: '='
        },
        link: function(scope, elem, attrs) {
          var Type;
          return new (Type = (function(_super) {
            __extends(Type, _super);

            function Type() {
              this.init();
              elem.addClass(this.$scope.discussionType["class"]);
            }

            Type.prototype.init = function() {
              Type.__super__.init.call(this, scope);
              return elem.on('click', (function(_this) {
                return function(evt) {
                  return _this.broadcast('UPDATE.DiscussionType', _this.$scope.discussionType);
                };
              })(this));
            };

            return Type;

          })(EventEmitter));
        }
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=discussionType.map
