// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('Pyoopil.Directives').directive('discussionTypes', [
    'EventEmitter', 'Notify', function(EventEmitter, Notify) {
      return {
        restrict: 'E',
        template: '<a ng-repeat="type in types" class="ques-icon" discussion-type="type"></a>',
        link: function(scope, elem, attrs) {
          var DiscussionTypes;
          return new (DiscussionTypes = (function() {
            function DiscussionTypes() {
              scope.types = [
                {
                  'name': 'question',
                  'class': 'ques',
                  'dialog': 'ques-box'
                }, {
                  'name': 'poll',
                  'class': 'poll',
                  'dialog': 'poll-box'
                }, {
                  'name': 'note',
                  'class': 'note-icon',
                  'dialog': 'note-box'
                }
              ];
            }

            return DiscussionTypes;

          })());
        }
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=discussionTypes.map
