// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('Pyoopil.Directives').directive('peoples', [
    'peopleService', 'Utilities', function(peopleService, Utilities) {
      return {
        restrict: 'E',
        template: '<ul><li class="follow-box" ng-repeat="people in peoples" people="people"></li></ul>',
        link: function(scope, elem, attrs) {
          var Peoples;
          return new (Peoples = (function() {
            function Peoples() {
              scope.peoples = [];
              this.addListeners();
            }

            Peoples.prototype.addListeners = function() {
              return scope.$on('READ.Peoples', (function(_this) {
                return function(evt, data) {
                  return _this.renderPeoples(evt, data);
                };
              })(this));
            };

            Peoples.prototype.renderPeoples = function(evt, peoples) {
              if (_.isEmpty(peoples)) {
                Notify.alert('No More Peoples to load', 'error');
                return;
              }
              return angular.forEach(peoples, function(people) {
                return scope.peoples.push(people);
              });
            };

            return Peoples;

          })());
        }
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=peoples.map
